### ISSUE TITLE
Automatic auth discovery inside AWS

### ISSUE THREAD

**Issue by BalmungSan** [d2a4u/sqs4s#126]
When running on EC2 / ECS / EKS you can attach roles directly to your application, instead of passing them explicit credentials.
The **Java** SDK is capable of [automatically finding](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials) the **ACCESS KEY**, **SECRET KEY** and **SESION_TOKEN** for authorizing your requests.

It would be great if this library would be able to do the same.

**Comment by d2a4u** [comment]
This would be great. Easy win would be using the Java lib but only the auth module or something. However, I think it should be fairly easy to stay purely Scala without using AWS SDK. I might be able to work on this feature this weekend, will post a branch here for visibility.

**Comment by d2a4u** [comment]
From the [AWS doc](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials) that you sent, this command gets the cred but requires a role (`s3access` in their example). However, in the [AWS SDK source code](https://github.com/aws/aws-sdk-java/blob/7b1e5b87b0bf03456df9e77716b14731adf9a7a7/aws-java-sdk-core/src/main/java/com/amazonaws/auth/InstanceMetadataServiceCredentialsFetcher.java#L65), looks like what they do is just getting the 1st one from a list of creds without specifying any role. I find this a bit weird, what do you think?

**Comment by BalmungSan** [comment]
For what I understand @d2a4u in the link I passed one requires to know beforehand the role name, this is impractical.
Also, AFAIK, you can only assign one role to each service / image / container / etc, so probably they know that the list can be either empty or be a single element list, so that is why they just access the first position _(+100 points to **Option** 😆)_.

**Comment by d2a4u** [comment]
I have opened a [draft PR](https://github.com/d2a4u/sqs4s/pull/128). I need to write more tests but I think the current logic should work, however, there is a piece of logic that I'm still not happy with but can't think of a better way to do it atm: https://github.com/d2a4u/sqs4s/pull/128/files#r453246432

**Comment by d2a4u** [comment]
@BalmungSan I have released 1.1.0. Cheers
