### ISSUE TITLE
Missing support for AWS Security Token Service (STS)

### ISSUE THREAD

**Issue by cpnielsen** [d2a4u/sqs4s#231]
Similar to https://github.com/d2a4u/sqs4s/issues/126, when searching for credentials inside a container running in a AWS kubernetes cluster (EKS) with an assigned service account and matching IAM role, the credentials are provided via the following env vars:

```sh
AWS_DEFAULT_REGION:              eu-central-1
AWS_REGION:                      eu-central-1
AWS_ROLE_ARN:                    arn:aws:iam::<ACCOUNT_ID>role/<ROLE>
AWS_WEB_IDENTITY_TOKEN_FILE:     /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

Currently `sqs4s` does not support this method of authentication.

The AWS Java SDK implementation can be found here: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sts/src/main/java/com/amazonaws/auth/STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java

Without this support, the credentials chain resolve to the EKS (EC2) node credentials, which in my case are not correct.

I _may_ be able to provide a "starting PR" with a naive implementation using the `temporaryCredentials` method and a call to the web identity token service.

Docs:
- [Associate an IAM role to a service account](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html)
- [Assume Role with Web Identity Token](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html)

**Comment by d2a4u** [comment]
@cpnielsen thanks for raising the issue. A starting PR would be amazing and I think you are right on track with using `temporaryCredentials`. I will also looking into the Java impl in the mean time. Cheers.

**Comment by cpnielsen** [comment]
@d2a4u As we discovered this as part of a larger set up on a deadline, we might use a workaround for now, and come back to this once we're through the weeds. If you haven't started on anything then, I'd be happy to contribute a PR.

**Comment by d2a4u** [comment]
@cpnielsen I have started some development for this feature, there is a branch here: https://github.com/d2a4u/sqs4s/blob/4b456bb243a48e258f771e7cdb55cc2a809b7a3d/native/src/main/scala/sqs4s/auth/Credentials.scala#L256

only rough code based on doc atm, hopefully I will be able to finish this by end of the week. But might need some help from you to test it out since I'm not quite familiar with EKS. Cheers

**Comment by cpnielsen** [comment]
> @cpnielsen I have started some development for this feature, there is a branch called `feature/sts`. Here is the impl:
> 
> https://github.com/d2a4u/sqs4s/blob/4b456bb243a48e258f771e7cdb55cc2a809b7a3d/native/src/main/scala/sqs4s/auth/Credentials.scala#L256
> 
> only rough code based on doc atm, hopefully I will be able to finish this by end of the week. But might need some help from you to test it out since I'm not quite familiar with EKS. Cheers

It looks very promising. I'd be happy to test it out as soon as you have something ready 👍

**Comment by d2a4u** [comment]
hi @cpnielsen, sorry for the delay on this. My laptop was broken and had to be sent away. Anyway, this PR is now ready: https://github.com/d2a4u/sqs4s/pull/246. This is the syntax to use STS: https://github.com/d2a4u/sqs4s/blob/b11d6e242448b120664291b3ae03d2224a7dab04/native/src/it/scala/sqs4s/api/hi/ClientItSpec.scala#L40. It would be great if you can help me testing it out. Thanks.

**Comment by cpnielsen** [comment]
@d2a4u I guess you can close this 😄

**Comment by cpnielsen** [comment]
Implemented 🚀
